// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhSMe3dDvFblaG5pF6GNGbUrBsZAeDfCI',
    appId: '1:569516680175:web:cff11ee3ed289c02624c1a',
    messagingSenderId: '569516680175',
    projectId: 'fozli-b9f2e',
    authDomain: 'fozli-b9f2e.firebaseapp.com',
    storageBucket: 'fozli-b9f2e.firebasestorage.app',
    measurementId: 'G-6Z6GHEX4VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBngZOZRpsW9QUB5VoOmgtMG02DhWE2KvM',
    appId: '1:569516680175:android:d998448401d94466624c1a',
    messagingSenderId: '569516680175',
    projectId: 'fozli-b9f2e',
    storageBucket: 'fozli-b9f2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB06coYPHgKJvABe6rYjsJ_f22M9NQ3JkM',
    appId: '1:569516680175:ios:788f68fd71ae83b3624c1a',
    messagingSenderId: '569516680175',
    projectId: 'fozli-b9f2e',
    storageBucket: 'fozli-b9f2e.firebasestorage.app',
    iosBundleId: 'com.example.fozli',
  );
}
